// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA8iwNCkGJ0jt6jAoR-WctCGwe7vJjCvmQ',
    appId: '1:653688654264:web:f17aac634b21c86f1d274d',
    messagingSenderId: '653688654264',
    projectId: 'rentora-67218',
    authDomain: 'rentora-67218.firebaseapp.com',
    storageBucket: 'rentora-67218.firebasestorage.app',
    measurementId: 'G-LKWS5C5WB4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDR8ApmbkpsNS3Lm14BZyVbvgNqldajRLo',
    appId: '1:653688654264:android:462c12b9b43a3abf1d274d',
    messagingSenderId: '653688654264',
    projectId: 'rentora-67218',
    storageBucket: 'rentora-67218.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB47KVcs1oQN7e6RlIV9NJ2_SjwbnORuQs',
    appId: '1:653688654264:ios:c0a142707e112fcf1d274d',
    messagingSenderId: '653688654264',
    projectId: 'rentora-67218',
    storageBucket: 'rentora-67218.firebasestorage.app',
    iosBundleId: 'com.example.rentora',
  );
}
